### ISSUE TITLE
Typo in Vignette 1's TL;DR Section

### ISSUE THREAD

**Issue by writingindy** [BaderLab/netDx#87]
# Description
In the TL;DR Section for vignette 1 (Building binary classifier from clinical and ’omic data using pathway-level features), the plotIntegratedPatientNetwork() function call has a typo for the prune_pctX argument. It has prune_X instead of prune_pctX as an argument for plotIntegratedPatientNetwork().

**Comment by shraddhapai** [comment]
TL;DR section of vignettes now removed.
